import uuid
from app.crud.base import CRUDBase

from datetime import datetime
from sqlalchemy.orm import Session
from sqlalchemy import and_

from app.models.user import User
from app.schemas.user import UserCreate, UserUpdate


user_crud = CRUDBase(User)

def create_user(db: Session, user_in: UserCreate):
    user = User(
        id=uuid.uuid4(),          # surrogate PK
        user_id=uuid.uuid4(),     # business key (generated by backend)
        version_no=1,             # first version
        **user_in.dict(),
    )

    db.add(user)
    db.commit()
    db.refresh(user)
    return user

def get_current_user_by_user_id(db: Session, user_id):
    return (
        db.query(User)
        .filter(
                and_(
                    User.user_id == user_id,
                    User.effective_end_dt.is_(None), # only active row
                )
            )
            .one_or_none()
        )

def scd2_update_user(
    db: Session,
    user_id,
    user_in: UserUpdate,
):
    # 1. Get current active row (latest version)
    current_user = (
        db.query(User)
        .filter(
            and_(
                User.user_id == user_id,          # business key
                User.effective_end_dt.is_(None),
            )
        )
        .one_or_none()
    )

    if not current_user:
        return None

    now = datetime.utcnow()

    # 2. Expire current row
    current_user.effective_end_dt = now
    current_user.updated_at = now

    # 3. Prepare data for new version
    new_data = current_user.__dict__.copy()
    new_data.pop("_sa_instance_state", None)

    # This is for Keys
    new_data["id"] = uuid.uuid4()                # For surrogate PK
    new_data["user_id"] = current_user.user_id   # For business key

    # 4️. Apply updates from request
    updates = user_in.dict(exclude_unset=True)
    new_data.update(updates)

    # 5. Versioning & dates
    new_data["version_no"] = current_user.version_no + 1
    new_data["effective_start_dt"] = now
    new_data["effective_end_dt"] = None
    new_data["updated_at"] = now

    # 6. Insert new row
    new_user = User(**new_data)
    db.add(new_user)
    db.commit()
    db.refresh(new_user)

    return new_user




